app/app/users/models.py
from datetime import datetime
from flask_login import UserMixin
from flask_security import RoleMixin
from app import db
from werkzeug.security import generate_password_hash, check_password_hash


roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('roles.id'))
)


class Role(db.Model, RoleMixin):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __str__(self):
        return self.name


class Users(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(64))
    email = db.Column(db.String(128), index=True, unique=True)
    password = db.Column(db.String(128))
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)
    updated_on = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)
    # Нужен для security!
    active = db.Column(db.Boolean())
    # Для получения доступа к связанным объектам
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


    # Flask-Security
    def has_role(self, *args):
        return set(args).issubset({role.name for role in self.roles})

    def get_id(self):
        return self.id

    # Required for administrative interface
    def __unicode__(self):
        return self.username
    
    def __repr__(self):
        return f'id:{self.id} {self.username}'

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/app/users/__init__.py
from flask import Blueprint


users = Blueprint('app_users', __name__, template_folder='templates', static_folder='static')


from .routes import login, logout, register, profile

app/app/users/routes.py
from flask import render_template, flash, redirect, url_for, request
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.urls import url_parse
from flask_login import login_required, login_user, logout_user, current_user
from app import db
from app import login_manager
from .models import Users
from app.users import users



@login_manager.user_loader
def load_user(id):
    return Users.query.get(int(id))


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('app_movies.view_movie'))


@users.route('/register', methods=["POST", "GET"])
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        pwd_1 = request.form['pwd-1']
        pwd_2 = request.form['pwd-2']
        generate_hash_1 = generate_password_hash(pwd_1)

        if len(name) < 3:
            flash("Short name", "error_name")
        elif email.find('@') == -1:
            flash("Incorrect email", "error_email")
        elif len(pwd_1) < 8:
            flash("Password must be at least 8 characters long, contain a capital letter and symbols", "error_pwd")

        elif not check_password_hash(generate_hash_1, pwd_2):
            flash("Passwords do not match", "error_pwd-2")
            # print("pasword - ok")
        else:
            try:
                user = Users(username=name, email=email, password=generate_hash_1)
                db.session.add(user)
                db.session.commit()
                flash("you have successfully registered")
                return redirect(url_for('app_users.login'))
            except Exception as error:
                print(error)
                flash("Save error user in DataBase", "error_save")
        print(name, email, pwd_1, pwd_2)
    return render_template('register.html')


@users.route('/login', methods=["POST", "GET"])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['pwd-1']
        remember = request.form.get('remember', False)
        print(email, password)
        user = Users.query.filter_by(email=email).first()

        if not user:
            flash("No correct email or password", "error_save")
            return redirect(url_for('app_users.login'))
        
        if check_password_hash(user.password, password):
            if remember:
                login_user(user, remember=remember)
            else:
                login_user(user)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('app_movies.view_movie')
            return redirect(next_page)
        else:
            flash("No correct email or password", "error_save")
            return redirect(url_for('app_users.login'))
    return render_template('login.html', form=request.form)


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user_id = current_user.id
    user = Users.query.filter_by(id=user_id).first()
    # if not chack_role_admin(user=user, role_name='Admin'):
    #     return redirect(url_for('app_users.login'))
    return render_template('user.html', user=user)

app/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/gh/maxshuty/accessible-web-components@latest/dist/simpleRange.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        
        <!-- Bootstrap CSS 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.css" integrity="sha512-SZgE3m1he0aEF3tIxxnz/3mXu/u/wlMNxQSnE0Cni9j/O8Gs+TjM9tm1NX34nRQ7GiLwUEzwuE3Wv2FLz2667w==" crossorigin="anonymous" />
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js" integrity="sha512-f0VlzJbcEB6KiW8ZVtL+5HWPDyW1+nJEjguZ5IVnSQkvZbwBt2RfCBY0CBO1PsMAqxxrG4Di6TfsCPP3ZRwKpA==" crossorigin="anonymous"></script>
        -->

        {% block title %}
        {% if title %}
            <title>Flask - {{title}}</title>
        {% else %}
            <title>Flask</title>
        {% endif %}
        {% endblock title %}
    </head>

    <body>
        <div class="container">
            <div class="row">
                {% include 'include/menu.html' %}

                {% block content %}

                {% endblock content %}
                
                {% include 'include/footer.html' %}
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        
    </body>
</html>

app/app/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="row justify-content-center gy-4">
        <div class="col-7">
            <h1 class="gy-5">{{title}}</h1>
        </div>
        <div class="col-5">
            <nav class="navbar navbar-expand-lg navbar-light bg-light gy-5">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarScroll">
                        {% include 'include/sorted.html' %}

                        {% include 'include/search.html' %}
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="row gy-4">
        <div class="col-2">
            {% include 'include/filters.html' %}
        </div>

        <div class="col-10">
            {% include 'include/list_card.html' %}
        </div>
    </div>
    {% if movies.count() > 0 %}
        {% include 'include/pagination.html' %}
    {% endif %}
{% endblock content %}

app/app/templates/login.html
{% extends 'base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}


{% block content %}

<h1>Sign In</h1>

<div class="row justify-content-center">
    <div class="col-4">
        <form action="{{ url_for('app_users.login') }}" method="post">
            {% for cat, msg in get_flashed_messages(True) %}
                {% if cat == 'success' %}
                    <div class="alert alert-success" role="alert">
                        <div class="form-text alert-success">{{msg}}</div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="mb-3">
                <label class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" placeholder="Your email">
            </div>
            <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="pwd-1" class="form-control" placeholder="Password">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" name="remember" class="form-check-input">
                <label class="form-check-label">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>


{% endblock content %}

app/app/templates/profile.html
{% extends 'base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}


{% block content %}

<div class="card" style="width: 18rem;">
    <img src="{{ url_for('static', filename=user.poster) }}" class="img-thumbnail" alt="">
    <div class="card-body">
        <h5 class="card-title">Settings profile</h5>
        <p class="card-text">Name: {{ user.name }}</p>
        <p class="card-text">Email: {{ user.email }}</p>
        <input  type="file" class="btn btn-info" value="change avatar">
        <br/>
        <a href="#" class="btn btn-primary">Save settings</a>
    </div>
</div>

{% endblock content %}

app/app/templates/register copy.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.poster.label }}<br>
            {{ form.poster }}<br>
            {% for error in form.poster.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/app/templates/register.html
{% extends 'base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}


{% block content %}

<h1>Register</h1>



<div class="row justify-content-center">
    <div class="col-4">
        <form action="{{ url_for('app_users.register') }}" method="post" novalidate>
            {% for cat, msg in get_flashed_messages(True) %}
                {% if cat == 'error_save' %}
                    <div class="alert alert-danger" role="alert">
                        <div class="form-text alert-danger">{{msg}}</div>
                    </div>
                {% endif %}
                {% if cat == 'success' %}
                    <div class="alert alert-success" role="alert">
                        <div class="form-text alert-success">{{msg}}</div>
                    </div>
                {% endif %}
            {% endfor %}
            
            <div class="mb-3">
                <label class="form-label">Your name</label>
                <input type="text" name="name" class="form-control" placeholder="Your name">
                {% for cat, msg in get_flashed_messages(True) %}
                    {% if cat == 'error_name' %}
                        <div class="alert alert-danger" role="alert">
                            <div class="form-text alert-danger">{{msg}}</div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-3">
                <label class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" placeholder="Your email">
                {% for cat, msg in get_flashed_messages(True) %}
                    {% if cat == 'error_email' %}
                        <div class="alert alert-danger" role="alert">
                            <div class="form-text alert-danger">{{msg}}</div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="pwd-1" class="form-control" placeholder="Password">
                {% for cat, msg in get_flashed_messages(True) %}
                    {% if cat == 'error_pwd' %}
                        <div class="alert alert-danger" role="alert">
                            <div class="form-text alert-danger">{{msg}}</div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="pwd-2" class="form-control" placeholder="Password">
                {% for cat, msg in get_flashed_messages(True) %}
                    {% if cat == 'error_pwd-2' %}
                        <div class="alert alert-danger" role="alert">
                            <div class="form-text alert-danger">{{msg}}</div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
         
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>



{% endblock content %}

app/app/templates/search.html
{% extends 'base.html' %}

{% block content %}

    <div class="row justify-content-center gy-4">
        <div class="col-7">
            <h1 class="gy-5">{{title}}</h1>
        </div>
        <div class="col-5">
            <nav class="navbar navbar-expand-lg navbar-light bg-light gy-5">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarScroll">
                        {% include 'include/search.html' %}
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="row gy-4">
        <div class="col-2"></div>
        <div class="col-10">
            {% include 'include/list_card.html' %}
        </div>
    </div>

    {% if movies.count() > 0 %}
        {% include 'include/pagination.html' %}
    {% endif %}

{% endblock content %}

app/app/templates/user.html
{% extends 'base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock title %}


{% block content %}

    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ url_for('static', filename=user.poster) }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Settings profile</h5>
                <p class="card-text">Name: {{ user.name }}</p>
                <p class="card-text">Email: {{ user.email }}</p>
                <input  type="file" class="btn btn-info" value="change avatar">
                <br/>
            <a href="#" class="btn btn-primary">Save settings</a>
            </div>
        </div>
        </div>
    </div>

{% endblock content %}